# model-zoo-models-private
models:
  - name: aclnet

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/aclnet/FP32/aclnet.xml
        weights: public/aclnet/FP32/aclnet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/aclnet/FP16/aclnet.xml
        weights: public/aclnet/FP16/aclnet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/aclnet/FP32-INT8/aclnet.xml
        weights: public/aclnet/FP32-INT8/aclnet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/aclnet/FP16-INT8/aclnet.xml
        weights: public/aclnet/FP16-INT8/aclnet.bin
        adapter: classification

    datasets:
      - name: wav-esc

        preprocessing:
          - type: resample_audio
            sample_rate: 16000
          - type: clip_audio
            duration: 1
            max_clips: 5
          - type: normalization
            std: 32768

        metrics:
          - type: accuracy
            name: top@1
            top_k: 1
          - type: accuracy
            name: top@5
            top_k: 5

global_definitions: ../dataset_definitions.yml
