models:
  - name: i3d-flow-tf
    launchers:
      - framework: dlsdk
        adapter: classification
        inputs:
          - name: Placeholder
            type: INPUT
            layout: NCDHW

    datasets:
      - name: kinetics-400-flows-79-400
        metrics:
          - type: clip_accuracy
            presenter: print_vector
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
