models:
  - name: vas-reidentification
    launchers:
    - framework: dlsdk
      adapter: reid
    datasets:
    - name: market1501
      preprocessing:
      - type: resize
        interpolation: LINEAR
        dst_width: 128
        dst_height: 256
      metrics:
      - type: normalized_embedding_accuracy

